services:
  api:
    restart: unless-stopped
    image: unmtransinfo/smartsfilter_api:latest
    container_name: smartsfilter-api
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:${APP_PORT:-8000}:8000"
    command: gunicorn --bind 0.0.0.0:8000 --reload app:app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/apidocs/').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
  ui:
    restart: unless-stopped
    image: unmtransinfo/smartsfilter_ui:latest
    container_name: smartsfilter-ui
    environment:
      - VITE_API_PROXY_TARGET=http://api:8000
    ports:
      - "127.0.0.1:${UI_PORT:-5173}:5173"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
