services: 
  web: 
    build:
      context: app
      dockerfile: Dockerfile
    env_file: 
      - .env.dev
    environment:
      - APP_PORT=${APP_PORT}
    ports: 
      - '${APP_PORT}:${APP_PORT}'   
